version: '3' 

services:

    # php-fpm
    app:
        build:
            context: ./dockerfiles
            dockerfile: app.dockerfile
        image: ${PROJECT_NAME}/app
        container_name: ${PROJECT_NAME}-app
        environment:
            VIRTUAL_HOST: "${PROJECT_NAME}.loc"
            XDEBUG_CONFIG: "remote_host=host.docker.internal mode=debug remote_port=${XDEBUG_REMOTE_PORT}"
            PHP_IDE_CONFIG: "serverName=${PROJECT_NAME}"
        volumes:
            - ./code:/var/www/html # code
            - ./config/php-ini:/usr/local/etc/php # php.ini
            - ./logs/php:/log/php # logs
        depends_on: 
            - db
        networks:
            - inner
        extra_hosts:
            host.docker.internal: host-gateway
        command: bash -c "/var/www/html/init.sh & php-fpm"
            
    
    # inner router
    router:
        build:
            context: ./dockerfiles
            dockerfile: static.dockerfile
        image: ${PROJECT_NAME}/router
        container_name: ${PROJECT_NAME}-router
        volumes:
            - ./code:/var/www/html
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - ./config/nginx/vhost.d:/etc/nginx/vhost.d
            - ./logs/nginx:/var/log/nginx
        restart: unless-stopped
        depends_on: 
            - app
        networks:
            - inner
        ports:
            - 8080:80
    
    # mysql | mariadb
    db:
        build:
            context: ./dockerfiles
            dockerfile: db.dockerfile
        image: ${PROJECT_NAME}/db
        container_name: ${PROJECT_NAME}-db
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_USER: "${PROJECT_NAME}"
            MYSQL_PASSWORD: "${PROJECT_NAME}"
            MYSQL_DATABASE: "${PROJECT_NAME}"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "${MYSQL_PORT}:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        networks:
            - inner
            
networks:
    inner:
        driver: bridge